skinparam classAttributeIconSize 0
skinparam monochrome true
skinparam shadowing false
skinparam roundCorner 0
skinparam class {
    BackgroundColor White
    BorderColor Black
    ArrowColor Black
}
hide empty members
hide circle
